# Default values
DOWNLOAD_URL=https://www.github.com/WluhWluh/BoomingSS/releases/latest
DONATION_LINK=https://ko-fi.com/christiaam
GITHUB_API_URL=https://api.github.com/
LYRICALLY_API_URL=https://lyrics.paxsenix.org/apple-music/lyrics

# F-Droid overrides
fdroid.DOWNLOAD_URL=https://www.github.com/WluhWluh/BoomingSS/releases/latest
fdroid.GITHUB_API_URL=

# Play Store overrides
playstore.DOWNLOAD_URL=https://www.github.com/WluhWluh/BoomingSS/releases/latest
playstore.DONATION_LINK=
playstore.GITHUB_API_URL=
playstore.LYRICALLY_API_URL=
